.travis.yml:
  sudo: true
  services:
    - docker
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: bmCVcTXl+kIgSqAyW4+KxCVu0cxP7R+FFpnm2xFC7Jz/T9qIML6imKW8z6fLr4u6qJAaQ04frrl5aB3lAwkJOPdKLvOgpWW59DSqczTsR7rIOxCmFbyZIkrtf72U8ozCQZa9SHMLrILS+8YVEvihJJp+AHJmyJKnXiP2opyrS03/iUnAYFMRv7YLG8tWutQsVYuom6mphJuXyp94Fw2Q+UpGxj6IGNi/lHW5y74Q4x0UYmTN92SbZnukxOyXGrpkfMch7cX3F2wxT74xbovKg9EYiiE0G0NjPZXkBVBlStKm8oqxrVE+LgxUiKak3iQ59RfCfgYQXrvdj/bShRnyZCUXfGxbsbzwcA/7IGSbIckU3hiAQY/TNCXV7Kft835FEtkKYmdCiDwhkJXk5H3Yach5C7DD05CXS513KLjAq7KLAWT/XUsOO5nnJ781ThH1XzZZyAfDkrhqfbTp7HMHOnAAOG32ho0SSWC6E8gVv3R72XBiFhGRY5M6wk9G99NPuDYLnu7Nk0I2/3R0KnyBZ/1lXkoxqzCu8W2ws+ZaibgeREaW8z9MOUZ+Nl1hKvcLCnRJx3ajtk+2Wp3bvlZYSLqSYzwOZJTOqiaSZ/qCJoXCiG4deDNqoqPnoE7tVPj0vWATmnl8Vmr4EHorcJTUpDiKsXyO81qje5nADJvA05c=
    api_key:
      secure: SkmG5RUr7HlfrI/VA8HufEBJKkZ/3fkeCSjHJVCjkaPgBWQShUJ38r2Zf2xOAwZb0cNsxc6pHsMF7RuVQovhN/DDYGo5GuhHG/mCjxOVy8b8j2w2+MBdq7L1Mxkye0giobATkjXzwGuCxxX/RVUnnL5skMtSEQqOv4m8wq1YGU6Trq1XYUT2/hKCAA6JPkNlNE1IIGWDgan6b3BcXgfMYKh0vzN6BETg4Wh9RmUksnsyG1xQ4TsUtz6JinQ0IPOHDxKdq4Ik6xUxKO/wDi7QPaxfFaqXHPqOEfuVouJfSOm1SN0tuj5JUrkVBT8D/HLrBUXieADJ/3mUs0ndQQyitOmw+AkTmh+OPumSpWk3X+BVUo7qyddl3YLuEaY524C7C4yfr2hkis81+G8xAx06hskel/CEK0mxZUgg5vNLtjWm1Caz69XG39G0+hcKnVIDIdUik/KU30lrlS+8f1JeQCN4BUFfO0BLEyxhJIPjV/MD7bUDJHVM1bsHFsAFQOW28mlpA3CVqPhhJUCAGXKJeY1e7ZzvvA65qU2f2OHGP0p0sdusvQaifnQP3c11D2yMVH9krQAGrMdcQR4F5HTBddkauS5PaM2OORt4R5HKuWlvBNR914Mj6HwCb/HcwYh0hWyrmMhzWt9dcFLRh/GgnLKonKio9RJN542BhyD5v6A=
