# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.3
- 1.7.3
services:
  - docker
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=medium
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: oLTXsHq+WwCYQys02c5CqbSjmA9N0AVoF0SwRsHGjlHhtSAb5+LaqRgcmm9VJctPFzFr6tfcWvfJDrvkhPk2zfgO3A7WSsCHxHzOq2iugPEV/kBI4YSqqqjEvsEEIJmWv5LGfVyc2uxBXV3XfQzLn96XsVo1ANkth8xPSZ7ogwQCtVmJZKdbjIXYga/dZUwqJ531iOBsgJjMI04ujocc3TjBFtp76wzz6jOmmLuMwYEUK726nqHpFm3+A9FxfVDx6qTOzGz/lrSyz4ICqxcfRjjMWoUVSG7ThU270UgHGD7DwlWstXVSZ5O+w7qGNZcIkBM9GYVolnbi6YspBqBKDbIoTbrRDPSHP+U5vc7OLVR5OmLH7I5fbmaLrNItqBuTdlMa2gtrkvrp3VYLKyY1rgykNz2qS1iL7rlIsmQfbdLrjq0mO1MQqifkLzNX68FG9WxFwhgbmkNfxSM3rinaG1SNYx1kp6QdEHQM0o00Cb1uw6pMoF89/9SPJX0CkrxHa7hqlFBKUtvoC0uKaSnMfRaORdkocu7iN+kUAkZDd7q4abqfcgUZe80RHuqWpJh9OZw+Bwd8S5Pqr0g1+EXWqgqThL1Wk19qYri629tcRR1zfobiNCzcUm3JReqyyiEEyE3kPfpipq1/8F/YCEPjfFnBBFiwfVr7O0jDBgKLBAQ=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-cassandra
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: oLTXsHq+WwCYQys02c5CqbSjmA9N0AVoF0SwRsHGjlHhtSAb5+LaqRgcmm9VJctPFzFr6tfcWvfJDrvkhPk2zfgO3A7WSsCHxHzOq2iugPEV/kBI4YSqqqjEvsEEIJmWv5LGfVyc2uxBXV3XfQzLn96XsVo1ANkth8xPSZ7ogwQCtVmJZKdbjIXYga/dZUwqJ531iOBsgJjMI04ujocc3TjBFtp76wzz6jOmmLuMwYEUK726nqHpFm3+A9FxfVDx6qTOzGz/lrSyz4ICqxcfRjjMWoUVSG7ThU270UgHGD7DwlWstXVSZ5O+w7qGNZcIkBM9GYVolnbi6YspBqBKDbIoTbrRDPSHP+U5vc7OLVR5OmLH7I5fbmaLrNItqBuTdlMa2gtrkvrp3VYLKyY1rgykNz2qS1iL7rlIsmQfbdLrjq0mO1MQqifkLzNX68FG9WxFwhgbmkNfxSM3rinaG1SNYx1kp6QdEHQM0o00Cb1uw6pMoF89/9SPJX0CkrxHa7hqlFBKUtvoC0uKaSnMfRaORdkocu7iN+kUAkZDd7q4abqfcgUZe80RHuqWpJh9OZw+Bwd8S5Pqr0g1+EXWqgqThL1Wk19qYri629tcRR1zfobiNCzcUm3JReqyyiEEyE3kPfpipq1/8F/YCEPjfFnBBFiwfVr7O0jDBgKLBAQ=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-cassandra
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: releases
  api_key:
    secure: fZRlieEjhmXvcj9yKiIRGYhHg99vlxpGaPOBNtRMHLdZZVprmndGXT04ieku0Lrxt9t001pAc9OmExLT8Ghf3zKmpK8sHwmijfPnKjJ5hsY6T43v517Ry165qs1zqn/dGYlxUACUgejLyWii7sKwFyiNgfKgTGbiX/MT67W40zY1M6w8pkVPeA4WmuvKGuxqCK9O2veP462ai5BONKw6JEnz4mewcZbzNSfHvCfTH5jp3VKSAts5oO2n0RodqoAJHIdFDkjOZ99NVZjKrIZkSmaVLCsUBSlXuQFlFOc9wCF93nRC2+dLpZp9dNHEzKIALprDEsfKd9Ubk/vR7LKvfSzzt3OfjNjJ04qjM+fX7yjO1D2VTRWMNNInhqRCv1LUtMZxUdUcxhH1aTr1Fj7BSVevC5IuRf15W/4/sRfMXurp12pYfJEDw/qQ0gU1camdGSJGlnUQAV0uhNoeDOCPtaVEhWrS2Qu/rEvyqsHGyFudqjufCAh8BumD/4vFw7kfIs8AWIoblwEOdt3T90nBVXHsbIs9WfO0he7lBjh1kmg5mHDvp2CSohN9GQ1mWcE8AvoLu93+CCHjhi2VNp9tdog1OVPQG+C/YPyfxEfKv+NCmhGVViek9tzvFYVyIC6Whm0yds+GuhSAjV93eYMk1OJ+TXfMHddK/NVcdbLwe4g=
  file:
    - release/snap-plugin-publisher-cassandra_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-publisher-cassandra
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
